version: "3.8"
networks:
  ccc-backend-network:
    external: false
services:
  ccc-backend:
    image: ccc-backend
    depends_on:
      - ccc-backend-db
    networks:
      - ccc-backend-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      # extern:intern
      - 3000:3000
    environment:
      - MONGO_DB_URL=mongodb://ccc-backend-db:27017
      - RPC_URL=http://host.docker.internal:8545
      - FARMLAND_REGISTRY_CONTRACT_ADDRESS=0xe69040B036FaF59C62455e826D971A22EE8EEcd0
      - CARBON_CREDIT_TOKEN_CONTRACT_ADDRESS=0x51CD2047C35c32f30a3B7bCC87c4A81794f8F804
  ccc-backend-db:
    image: mongo:4.4.1-bionic
    networks:
      - ccc-backend-network
    volumes:
      - ../data/ccc-backend:/data/db